spring:
  application:
    name: addressbook
  profiles:
    active: default

server:
  port: 9093

management:
  endpoints.web.exposure.include: health

logging:
  level:
    io.naraway: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%5p) [${spring.application.name:-},%X{traceId:-},%X{spanId:-}] [${PID:- }] [%15.15t] %clr(%-60.60logger{59}){cyan} : %m%n%wEx'

nara:
  janitor:
    id: io.naraway.addressbook
    subscriptions: >
      io.naraway.addressbook
    mode: local
    bootstrap-address: localhost:9092
  signing-key: secret
  test-profiles: default,k8s-test

---
spring:
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: ${spring.application.name}
      database: ${spring.application.name}
      username: ${spring.application.name}
      password: ${spring.application.name}

nara:
  janitor:
    mode: local
  drama:
    default:
      actorId: 1@1:1:1:1-1
      loginId: user@company.io
      displayName: Manager
      citizenId: 1@1:1:1
      cineroomIds: 1:1:1:1,1:1:1:2,1:1:1:3

---
spring:
  config:
    activate:
      on-profile: k8s
  data:
    mongodb:
      uri: ${datasource.uri:}
      host: ${datasource.host:}
      port: ${datasource.port:27017}
      authentication-database: ${datasource.name:}
      database: ${datasource.name:}
      username: ${datasource.username:}
      password: ${datasource.password:}

server:
  port: 8080

logging:
  level:
    root: ${logging.level.root}

springfox:
  documentation:
    enabled: true

nara:
  swagger:
    basePath: /api/${spring.application.name}
  janitor:
    mode: ${janitor.mode}
    bootstrap-address: ${janitor.bootstrap-address}
